_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  IMS_PER_BATCH: 20
  MAX_ITER: 35000
  WARMUP_ITERS: 300
  CHECKPOINT_PERIOD: 500
OUTPUT_DIR: "output/fcos/R_101_2x_small_batch"
