_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 128
  MAX_ITER: 5000
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 500
