_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: 'https://download.pytorch.org/models/resnext50_32x4d-7cdf4587.pth'
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 4
    DEPTH: 50
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT_DIR: "output/fcos/X_50_1x"
